###
get http://127.0.0.1:3000/


###
post http://127.0.0.1:3000/api/register
###
post http://127.0.0.1:3000/api/login


###
post http://127.0.0.1:3000/api/register
Content-Type: application/x-www-form-urlencoded

username=
&password=

###
post http://127.0.0.1:3000/api/login
