###
get http://127.0.0.1:3000/


###
post http://127.0.0.1:3000/api/register
###
post http://127.0.0.1:3000/api/login


###
post http://127.0.0.1:3000/api/register
Content-Type: application/x-www-form-urlencoded

username=
&password=

###
# @name login
post http://127.0.0.1:3000/api/login
Content-Type: application/x-www-form-urlencoded

username=abaaba
&password=bababa


###
get http://127.0.0.1:3000/abaaba/login
Content-Type: application/x-www-form-urlencoded
Authorization: {{token}}


###
get http://127.0.0.1:3000/my/userInfo
Content-Type: application/x-www-form-urlencoded
Authorization: {{token}}


###
post http://127.0.0.1:3000/my/userInfo
Content-Type: application/x-www-form-urlencoded
Authorization: {{token}}

id=6
&nickname=abab
&email=abab@abab.com


###
post http://127.0.0.1:3000/my/updateUserPwd
Content-Type: application/x-www-form-urlencoded
Authorization: {{token}}

oldPwd=bibibi
&newPwd=bababa


###
post http://127.0.0.1:3000/my/update/avatar
Content-Type: application/x-www-form-urlencoded
Authorization: {{token}}

avatar=data:image/gif;base64,R0lGODlhAQABAIAAAAUEBAAAACwAAAAAAQABAAACAkQBADs=


###
get http://127.0.0.1:3000/my/article/cates
Content-Type: application/x-www-form-urlencoded
Authorization: {{token}}


###
post http://127.0.0.1:3000/my/article/addcates
Content-Type: application/x-www-form-urlencoded
Authorization: {{token}}

name=数学
&alias=ShuXue


### variables
@token = {{login.response.body.token}}
